# create table USER
drop table if exists USER;
CREATE TABLE USER (
    ID INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(255) DEFAULT  NULL,
    PASSWORD VARCHAR(255) DEFAULT  NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=UTF8;
INSERT INTO USER VALUES ('1', 'admin', '1234');

# create table category
DROP TABLE IF EXISTS CATEGORY;
CREATE TABLE CATEGORY(
                         ID INT(11) NOT NULL ,
                         NAME VARCHAR(255) NOT NULL ,
                         PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

# create table book
DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    COVER VARCHAR(255) DEFAULT '',
    TITLE VARCHAR(255) NOT NULL DEFAULT '',
    AUTHOR VARCHAR(255) DEFAULT '',
    DATE VARCHAR(20) DEFAULT '',
    PRESS VARCHAR(255) DEFAULT '',
    ABS VARCHAR(255) DEFAULT NULL,
    CID INT(11) DEFAULT NULL,
    PRIMARY KEY (ID),
    KEY FK_BOOK_CATEGORY_ON_CID (CID),
    CONSTRAINT FK_BOOK_CATEGORY_ON_CID FOREIGN KEY (CID) REFERENCES CATEGORY (ID) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=102 DEFAULT CHARSET=utf8;

