version: '3.7'
services:
    db:
        container_name: dev-db
        image: mysql:latest
        ports:
            - "3306:3306"
        volumes:
            - ./Database/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: DEV_DB
            MYSQL_USER: admin
            MYSQL_PASSWORD: passw0rd
        restart: always

##   server
#    app:
#        image: adoptopenjdk/openjdk11:alpine
#        container_name: server
#        volumes:
#            -   ./server:/app
##        build:
##            context: ./server
##            dockerfile: ./Dockerfile
#        depends_on:
#            -   db
#        ports:
#            -   "8443:8443"
#        restart: always

#   client
    app2:
        image: node:lts-alpine
        container_name: client
        working_dir: /app
        volumes:
            -   ./client:/app
        ports:
            - "8080:8080"
        privileged: true
        tty: true
        stdin_open: true
        depends_on:
            -   db

