version: '3.7'
services:
    db:
        container_name: db
        image: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./Database/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: DEV_DB
            MYSQL_USER: admin
            MYSQL_PASSWORD: passw0rd

    app:
        container_name: ap1
        build:
            context: ./server
        depends_on:
            -   db
        ports:
            -   "8443:8443"

