version: '3.7'
services:
    db:
        container_name: jotter_db
        image: mysql:latest
        ports:
            - "3306:3306"
        volumes:
            - ./Database/data:/var/lib/mysql
            - ./Database/init/tables.sql:/docker-entrypoint-initdb.d/1.sql
            - ./Database/init/data.sql:/docker-entrypoint-initdb.d/2.sql
            - ./Database/my.cnf:/etc/mysql/conf.d/my.cnf
        env_file: Database/config.env
        restart: always

##   server
    app:
        container_name: server
        build:
            context: ./server
            dockerfile: ./Dockerfile
        depends_on:
            -   jotter_db
        ports:
            -   "8443:8443"
        restart: always

#   client
    app2:
        container_name: client
        build:
            context: ./client
            dockerfile: ./Dockerfile
        privileged: true
        tty: true
        stdin_open: true
        depends_on:
            -   db
        ports:
            -   "8080:8080"
        command: npm run dev

