
drop table if exists USER;

CREATE TABLE USER (
    ID INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(255) DEFAULT  NULL,
    PASSWORD VARCHAR(255) DEFAULT  NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=UTF8;

INSERT INTO USER VALUES ('1', 'admin', '1234');